CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18),       
   PRIMARY KEY (ID)
);


ALTER TABLE CUSTOMER ADD PRIMARY KEY (ID);
